import mongoose from 'mongoose';

const blogPostSchema = new mongoose.Schema(
    {
        title: { type: String, required: true, trim: true },
        subtitle: { type: String },
        contentHtml: { type: String, required: true },
        summary: { type: String },
        bannerImageUrl: { type: String },
        imageUrls: [{ type: String }],
        category: { type: mongoose.Schema.Types.ObjectId, ref: 'Category' },
        tags: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Tag' }],
        author: { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },
        status: { type: String, enum: ['draft', 'published', 'scheduled', 'auto-generated'], default: 'draft', index: true },
        isFeatured: { type: Boolean, default: false, index: true },
        views: { type: Number, default: 0, index: true },
        likes: { type: Number, default: 0 },
        readingTimeMinutes: { type: Number, default: 0 },
        publishedAt: { type: Date, index: true },
        slug: { type: String, unique: true, index: true },
        metaTitle: { type: String },
        metaDescription: { type: String },
        trendScore: { type: Number, default: 0, index: true },
        autoGeneratedBy: { type: String },
    },
    { timestamps: true }
);

blogPostSchema.index({ title: 'text', subtitle: 'text', contentHtml: 'text' });

export default mongoose.model('BlogPost', blogPostSchema);


